# Automatically generated file. DO NOT MODIFY

# This file is generated by device/leeco/msm8996-common/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/leeco/msm8996-common/proprietary
endif
